[theme]
base = "light"
primaryColor = "#8f1d2c"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#161513"
font = "serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showSidebarNavigation = false
